# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Runs unit tests"
  lane :tests do
    sh('mv ./../brain-marks/Secrets-CI.swift ./../brain-marks/Secrets.swift')
    scan
  end
end
